app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['domain' => 'cron.tibiacharts.com'], function()
{
    Route::get('/map', 'CronController@cronMap');
    Route::get('/houses', 'CronController@HouseCronJob');
});

Route::group(['middleware' => 'web', 'prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('setCookie', 'Controller@setCookie');
    Route::get('getCookie/{name}', 'Controller@getCookie');

    Route::get('/', 'HomeController@index');

    Route::get('/home', 'HomeController@index');

//    Route::get('/characters', 'PlayerController@indexPlayers');
//    Route::post('/characters', 'PlayerController@indexPlayers');
//
    Route::get('/logs', 'LogsSystemController@index');
    Route::post('/logs', 'LogsSystemController@store');
    Route::get('/log/{code}', 'LogsSystemController@indexLog');
//
//    Route::get('/events', 'EventController@index');

    Route::match(['get','post'], '/maps', 'HouseController@index');

    Route::match(['get','post'], '/houses', 'HouseController@index');
    Route::get('/getHouse', 'HouseController@getHouse');
    Route::get('/alertHouse', 'HouseController@alertHouse');
    Route::get('/listHouses', 'HouseController@listHouses');

    Route::match(['get', 'post'], '/npcs', 'NpcController@index');
    Route::get('/getNpc', 'NpcController@getNpc');
    Route::get('/listNpcs', 'NpcController@listNpcs');

    Route::match(['get','post'], '/hunts', 'HuntController@index');
    Route::get('/getHunt', 'HuntController@getHunt');
    Route::get('/listHunts', 'HuntController@listHunts');

    Route::match(['get','post'], '/races', 'RaceController@index');
    Route::match(['get','post'], '/bosses', 'RaceController@bosses');
    Route::get('/getRace', 'RaceController@getRace');
    Route::get('/listRaces', 'RaceController@listRaces');
    Route::get('/getKills', 'Races_killController@getKills');




    /* Route for Cronjobs */
    Route::group(['prefix'=>'cron'], function(){
        Route::get('/houses', 'HouseStatusController@cronHouses');
        Route::get('/auctionedHouses', 'HouseStatusController@cronHousesAuctioned');
        Route::get('/worlds', 'WorldController@cronWorld');
        Route::get('/npcs/{url?}', 'NpcController@cronNpc');
        Route::get('/races', 'RaceController@cronRacesWiki');
        Route::get('/normalraces', 'RaceController@getRacesContent');
        Route::get('/killstatistics', 'Races_killController@cronKillStatistics');
        Route::get('/itens/{url?}', 'ItenController@cronItens');

    });

    /* Route for ADMIN */
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){

        Route::get('', 'UserController@indexAdmin');

        Route::get('scripts/{tipo?}', 'ScriptsController@index');

        Route::get('crop', 'CropImageController@index');
        Route::post('crop', 'CropImageController@crop');

        Route::get('users', 'UserController@indexAdmin');
        Route::put('users', 'UserController@store');
        Route::patch('users', 'UserController@update');
        Route::delete('users', 'UserController@delete');

        Route::get('home', 'UserController@indexAdmin');

        Route::get('npcs', 'NpcController@indexAdmin');
        Route::get('getDataNpc', 'NpcController@getDataNpc');
        Route::put('npcs', 'NpcController@store');
        Route::patch('npcs', 'NpcController@update');


        Route::get('professions', 'ProfessionController@indexAdmin');
        Route::put('professions', 'ProfessionController@store');
        Route::patch('professions', 'ProfessionController@update');
        Route::delete('professions', 'ProfessionController@delete');
        Route::get('getDataProfession', 'NpcController@getDataProfession');


        Route::get('houses', 'HouseController@indexAdmin');
        Route::patch('houses', 'HouseController@update');

        Route::get('races', 'RaceController@indexAdmin');
        Route::put('races', 'RaceController@store');
        Route::patch('races', 'RaceController@update');
        Route::delete('races', 'RaceController@delete');

        Route::get('getRacesMap', 'Race_mapController@getRacesMap');
        Route::get('getRaceMap', 'Race_mapController@getRaceMap');

        Route::put('races_map', 'Race_mapController@store');
        Route::patch('races_map', 'Race_mapController@update');
        Route::delete('races_map', 'Race_mapController@delete');


        Route::get('hunts', 'HuntController@indexAdmin');
        Route::put('hunts', 'HuntController@store');
        Route::patch('hunts', 'HuntController@update');
        Route::delete('hunts', 'HuntController@delete');

        Route::get('getPlaces', 'Hunts_PlaceController@getPlaces');
        Route::get('getPlace', 'Hunts_PlaceController@getPlace');
        Route::get('getRaces', 'Hunts_PlaceController@getRaces');

        Route::put('places', 'Hunts_PlaceController@store');
        Route::patch('places', 'Hunts_PlaceController@update');
        Route::delete('places', 'Hunts_PlaceController@delete');

        Route::put('place_race', 'Place_RaceController@store');
        Route::delete('place_race', 'Place_RaceController@delete');

        Route::get('events', 'EventController@indexAdmin');
        Route::put('events', 'EventController@store');
        Route::patch('events', 'EventController@update');
        Route::delete('events', 'EventController@delete');

        Route::get('/map', 'MapController@indexAdmin');
        Route::post('/map', 'MapController@generate');

    });

    Route::auth();

});

app/House.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class House extends Model
{

    protected $fillable = ['coord', 'floor', 'town_id'];
    public $timestamps = false;


    public function town()
    {
        return $this->belongsTo(Town::class);
    }



    public function status()
    {
        return $this->hasMany(HouseStatus::class);
    }



    public function alert()
    {
        return $this->hasMany(UserHouseAlert::class);
    }



    public function getRealFloorAttribute()
    {
        return (($this->attributes['floor'] -7) * (-1));
    }



    public function getCoordXAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        $center = ($coords[0]+$coords[2])/2;
        return $center;

    }



    public function getCoordYAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        $center = ($coords[1]+$coords[3])/2;
        return $center;
    }



    public function getNameDecodedAttribute()
    {
        return urlencode($this->attributes['name']);
    }



    public function getNameUtf8Attribute()
    {
        return str_replace("&nbsp;"," ",htmlentities($this->attributes['name'], ENT_QUOTES, "UTF-8"));
    }


    public function getTypeAttribute()
    {
        return ucfirst($this->attributes['type']);
    }



    public function getCoordAuxAttribute()
    {
        if ($this->attributes['coord'] == '') {
            $town = Town::where('id',$this->attributes['town_id'])->first();
            return $town->coord;
        }
    }

}

app/HouseStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HouseStatus extends Model
{
    
    public $timestamps = false;
    
    protected $table = 'houses_status';
    
    public static $url = 'subtopic=houses';
    public static $urlBase = 'https://secure.tibia.com/community/?';
    
    
    
    public function house() 
    {
        return $this->belongsTo(House::class);
    }
    
    
    
    public function world() 
    {
        return $this->belongsTo(World::class);
    }
    
    
    
    public function town() 
    {
        return $this->belongsTo(Town::class);
    }
    

    
    public function getLastUpdateFormatedAttribute()
    {
        
        $date = $this->attributes['last_update'];
        
        return implode('/',array_reverse(explode('-', $date)));
    }
    
    
    
    public function getSimpleStatusAttribute()
    {
        preg_match('/(?P<status>[^(]*)/',$this->attributes['status'],$match);
        
        return $match['status'];
    }
    
    
    
    public function getTimeStatusAttribute()
    {
        preg_match('/(\((?P<left>.*)\))$/',$this->attributes['status'],$match);
        
        if (!empty($match['left'])) {
            return explode(';',$match['left']);
        }
    }
    
    
    public function getColorAttribute() 
    {
        $status = $this->attributes['status'];
        
        switch($status) {
            case 'rented':
                return "#FF0000";
                
            case 'auctioned (no bid yet)':
                return "#00FF00";
                
            default:
                return '#FFFF00';
            
        }
    }
    
    
    public function getBtnAttribute()
    {
        
        $status = $this->attributes['status'];
        
        switch($status) {
            case 'rented':
                return 'danger';
                
            case 'auctioned (no bid yet)':
                return 'success';
                
            default:
                return 'warning';
            
        }
        
        
    }
    
    
    
    /* script to capture houses status from tibia.com */
    public static function getHousesContent($world = '', $town = '') 
    {
        $types = array('houses', 'guildhalls');
        $housesArray = array();
        $stringTd = '';
        
        foreach ($types as $type) {
            $post = 'world='.$world.'&town='.$town.'&type='.$type;
            $tables = getData(self::$urlBase.self::$url, $post);           
           
            foreach($tables['tr>td'] as $tr) {
                
                $td = $tr->nodeValue;
                
                if (stristr($td,'World')==false
                    && stristr($td,'Available ')==false
                    && stristr($td,'Name')==false
                    && stristr($td,'Size')==false
                    && strstr($td,'Rent')==false
                    && stristr($td,'Status')==false) 
                {

                    if (strlen($td)>2) {
                        $td = utf8_decode(str_replace('&Acirc;','', $td));
                        $stringTd .= $td.'|';

                    } else {

                        if (!empty($stringTd)) {
                            $arrayTd =  explode('|', $stringTd);
                            $arrayTd[4] = substr($type,0,-1);

                            if (count($arrayTd)==5) {
                                    array_push($housesArray, $arrayTd);
                            }

                            $stringTd = '';
                        }
                    }
                }
            }
        }

        return $housesArray;

    }
    
    
    
    /* script to capture unique house status from tibia.com */
    public static function getHouseContent($world, $town, $house_id) 
    {
        self::$url = 'subtopic=houses&page=view';
        $housesArray = array();
        $stringTd = '';
        

        $post = 'world='.$world.'&town='.urlencode($town).'&houseid='.$house_id;
        $tables = getData(self::$urlBase.self::$url, $post);           

        preg_match('/The auction(?P<content>.*)/', $tables, $match);

        if (empty($match['content'])) {
            return false;
        }
        preg_match('/will end at (?P<time>.*)CEST.* is <b>(?P<gold>.*) gold.*by (?P<player>.*)\./',utf8_encode($match['content']),$housesArray);

        return $housesArray;

    }
    
   
}

app/Npc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Npc extends Model
{    
    
    public static $url = 'Lista_de_NPCs_por_Localiza%C3%A7%C3%A3o';
    public static $urlBase = 'http://www.tibiawiki.com.br/wiki/';
    
    protected $fillable = ['name', 'town_id', 'coord', 'floor', 'observation', 'profession_id'];
    public $timestamps = false;
    
    
    public function town() 
    {
        return $this->belongsTo(Town::class);
    }

    
    
    public function profession() 
    {
        return $this->belongsTo(Profession::class);
    }
    
    
    
    public function getRealFloorAttribute() 
    { 
        return (($this->attributes['floor'] -7) * (-1));
    }
    
    
    
    public function getImagePathAttribute() 
    {
        if (empty($arrayImg)) {
            $arrayImg = getImgs('npcs');
        }
        $path = '/images/npcs/'.imgMatch($arrayImg, $this->attributes['name']).'.gif';
        
        return $path;
    }
    
    
    
    public function getNameDecodedAttribute()
    {
        return str_replace("'","&apos;",$this->attributes['name']);
    }
    
    
    
    public function getNameUrlAttribute()
    {
        return str_replace(" ","_",$this->attributes['name']);
    }
    
    
    
     public function getCoordXAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[0]+1005);
        
    }
    
    
    
    public function getObservationTransAttribute()
    {
        $locale = \App::getLocale();
        
        $text = $this->attributes['observation'];

        preg_match('/\<'.$locale.'>(?P<translated>.*)\<\/'.$locale.'\>/', $text, $match);
        
        if (!empty($match['translated'])) {
            return ($match['translated']);
        } else {
            return '';
        }

        
    }
    
    
    
    public function getCoordYAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[1]+1025);
        
    }
    
    
    /* script to capture npcs from tibiawiki */
    public static function getNpcsContent() 
    {

        $npcArray = array();
        $arrayTd = array();
        
        $tables = getData(self::$urlBase . self::$url,'','.sortable');

        $line = 1;
        foreach($tables['tr>td'] as $tr) {

            $td = $tr->nodeValue;
        
            $find = array('/\s+\s+/', '/\n/');
            $replace = array('\s+', '');
            $arrayTd[$line] = preg_replace($find, $replace, $td);
            
            if ($line==5) {
                array_push($npcArray, $arrayTd);
                
                $line = 1;
                $arrayTd = array();
            } else {
                $line++;
            }
            
         }

        return $npcArray;

    }
 
}

app/Profession.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profession extends Model
{    
    
    
    protected $fillable = ['name'];
    public $timestamps = false;
    
    
    
    public function getProfessionTransAttribute()
    {
        $locale = \App::getLocale();
        
        $text = $this->attributes['name'];

        preg_match('/\<'.$locale.'>(?P<translated>.*)\<\/'.$locale.'\>/', $text, $match);
        
        if (!empty($match['translated'])) {
            return ($match['translated']);
        } else {
            return '';
        }
        
    }
 
}

resources/views/ajax/house.blade.php
@extends('ajax.layout')

@section('content')

<div class="row">
    <div class="col-md-8 col-sm-8 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">{{ $status->house->type }}</p>
              <h4 class="list-group-item-heading">{{ $status->house->name }}</h4>

            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.size')</p>
              <h4 class="list-group-item-heading">{{ $status->house->size }} sqm</h4>

            </div>
        </div>
    </div>
    <div class="col-md-8 col-sm-8 col-xs-12">
        <div class="list-group">
            <div class="list-group-item  list-group-item-{{ $status->btn }}">
              <p class="list-group-item-text">@lang('texts.status')</p>
              <h4 class="list-group-item-heading">{{ $status->simple_status }}</h4>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.rent')</p>
              <h4 class="list-group-item-heading">{{ $status->house->rent }} gps</h4>

            </div>
        </div>
    </div>
    @if (!empty($status->time_status[0]))
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.bid')</p>
              <h4 class="list-group-item-heading">{{ $status->time_status[0] }}</h4>
            </div>
        </div>
    </div>
    @endif

    @if (!empty($status->time_status[1]))
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.time_left')</p>
              <h4 class="list-group-item-heading">{{ $status->time_status[1] }}</h4>
            </div>
        </div>
    </div>
    @endif
</div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.last_update')</p>
              <h4 class="list-group-item-heading">{{ $status->last_update_formated }}</h4>

            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">

                <form action="https://secure.tibia.com/community/?subtopic=houses&page=view" method="post" target="_blank">
                    <input type="hidden" name="world" value="{{ $status->world->name }}">
                    <input type="hidden" name="town" value="{{ $status->town->name }}">
                    <input type="hidden" name="state" value="">
                    <input type="hidden" name="type" value="houses">
                    <input type="hidden" name="order" value="">
                    <input type="hidden" name="houseid" value="{{ $status->house->idtibia }}">
                    <button type="submit" class="btn btn-block btn-info" style="padding: 20px" name="View" alt="View">@lang('texts.checkin') Tibia.com</button>
                </form>


    </div>
</div>
@endsection

resources/views/ajax/hunt.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.location')</p>
              <h4 class="list-group-item-heading">{{ $place->hunt->name }} <small>{{ $place->title }}</small></h4>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.level')</p>
              <h4 class="list-group-item-heading">{{ $place->hunt->level }}</h4>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.creatures')</p>
              <div class="row-heigth">
              @foreach($place->races as $race)
              <div class="col-md-4 col-sm-4 col-xs-4 text-center"><h6>{{ $race->name }}<br /><small>Exp: {{ $race->exp }}</small></h6><img src="{{ $race->image_path }}" /></div>
              @endforeach
              </div>
              <div class="clearfix"></div>
            </div>
            
        </div>
    </div>
</div>

@endsection

resources/views/ajax/layout.blade.php
<!DOCTYPE html>
<html>
    <body class="sidebar-mini skin-black">
        @yield('content')
    </body>
</html>

resources/views/ajax/list_houses.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.houses_guildhalls')</div>
              <div class="panel-body">
                    <div class="row col-md-12">
                        <form id="form" class="box" method="post">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="box-body">
                                <div class="col-sm-12 col-md-8 col-lg-6">
                                    <div class="form-group">
                                        <label>@lang('texts.select_order')</label>
                                        <select class="form-control" id="changeorder" name="order">
                                            <option value=""></option>
                                            <option value="name">@lang('texts.name')</option>
                                            <option value="size">@lang('texts.size')</option>
                                            <option value="rent">@lang('texts.rent')</option>
                                        </select>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                    @foreach ($houses as $value)
                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                        <div class="house-unit house-{{ $value->btn }}" data-coord_x="{{ $value->house->coord_x}}"  data-coord_y="{{ $value->house->coord_y}}" data-floor="{{ $value->house->floor}}">
                            <dtitle>{{ $value->town->name }} - {{ $value->house->type }}</dtitle>
                            <hr>

                            <div class="col-md-12">
                                <h4>{{ $value->house->name_utf8 }}</h4>
                            </div>

                            <hr>
                            <div class="col-md-12">
                                <span class="pull-left">{{ $value->house->size }} sqm </span> <span class="pull-right"> {{ $value->house->rent }} gps  </span>
                                <div class="clearfix"></div>
                            </div>

                        </div>
                    </div>
                    @endforeach
                </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script>
 $(document).ready(function(){
    $('.house-unit').click(function(){
        var start_x = $(this).data('coord_x');
        var start_y = $(this).data('coord_y');
        var floor = $(this).data('floor');
        var start_zoom = 7;

        Init(start_x,start_y,floor,start_zoom);

        $('html, body').animate({
            scrollTop: $("#showMap").offset().top-50
        }, 1000);

    });

    $('#changeorder').change(function(){
        listHouse();
    });
});
</script>
@endsection

resources/views/ajax/list_hunts.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="dash-unit">
            <dtitle>@lang('texts.hunts')</dtitle>
            <hr>
            @foreach ($places as $place)
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                <div class="hunt-unit hunt-box" data-coord_x="{{ $place->coord_x }}"  data-coord_y="{{ $place->coord_y }}" data-floor="{{ $place->floor }}">
                    <h4>{{ $place->hunt->name }} </h4>
                    <h5>{{ $place->title }}</h5>

                </div>
            </div>
            @endforeach
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script>
    $('.hunt-unit').click(function(){
        var start_x = $(this).data('coord_x');
        var start_y = $(this).data('coord_y');
        var floor = $(this).data('floor');
        var start_zoom = 5;

        Init(start_x,start_y,floor,start_zoom);

        $('html, body').animate({
            scrollTop: $("#showMap").offset().top-50
        }, 1000);

    });
</script>
@endsection

resources/views/ajax/list_npcs.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.npcs')</div>

            <div class="panel-body">
                  @foreach ($npcs as $value)
                  <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                      <div class="npc-unit" data-coord_x="{{ $value->coord_x}}"  data-coord_y="{{ $value->coord_y}}" data-floor="{{ $value->floor}}">
                          <dtitle>{{ $value->name }} </dtitle>
                          <hr>

                          <div class="col-md-12">
                              <h4>{{ $value->town->name }}</h4>
                          </div>

                      </div>
                  </div>
                  @endforeach
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script>
    $('.npc-unit').click(function(){
        var start_x = $(this).data('coord_x');
        var start_y = $(this).data('coord_y');
        var floor = $(this).data('floor');
        var start_zoom = 5;

        Init(start_x,start_y,floor,start_zoom);

        $('html, body').animate({
            scrollTop: $("#showMap").offset().top-50
        }, 1000);

    });
</script>
@endsection

resources/views/ajax/list_races.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
          <div class="panel-heading">@lang('texts.races')</div>

          <div class="panel-body">

                @foreach ($coords as $i=>$coord)
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="race-unit" data-coord_x="{{ $coord->x }}"  data-coord_y="{{ $coord->y }}" data-floor="{{ $coord->floor}}">
                      <dtitle>{{ $race->name }} </dtitle>
                      <hr>

                      <div class="col-md-12">
                          <h4>{{ $coord->town }}</h4>
                      </div>

                    </div>
                </div>
                @endforeach
          </div>
          <div class="clearfix"></div>
      </div>
    </div>
</div>
<script>
    $('.race-unit').click(function(){
        var start_x = $(this).data('coord_x');
        var start_y = $(this).data('coord_y');
        var floor = $(this).data('floor');
        var start_zoom = 5;

        Init(start_x,start_y,floor,start_zoom);

        $('html, body').animate({
            scrollTop: $("#showMap").offset().top-50
        }, 1000);

    });
</script>
@endsection

resources/views/ajax/npc.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.name')</p>
              <h4 class="list-group-item-heading">{{ $npc->name }}</h4>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.profession')</p>
              <h4 class="list-group-item-heading">{{ $npc->profession->profession_trans }}</h4>
            </div>
        </div>
    </div>
 </div>   
@if (!empty($npc->observation_trans))
<div class="row">
    <div class="col-md-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.observation'):</p>
              <h4 class="list-group-item-heading">{{ $npc->observation_trans }}</h4>
            </div>
        </div>
    </div>
</div>
@endif
</div>

@endsection

resources/views/ajax/race.blade.php
@extends('ajax.layout')

@section('content')
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.name')</p>
              <h4 class="list-group-item-heading">{{ $race->name }}</h4>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item text-center">
              <img src="{{ $race->image_path }}" />
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.hp')</p>
              <h4 class="list-group-item-heading">{{ $race->hp }}</h4>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
              <p class="list-group-item-text">@lang('texts.exp')</p>
              <h4 class="list-group-item-heading">{{ $race->exp }}</h4>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="list-group">
            <div class="list-group-item">
                <h4>Kill Statistics</h4>
                <div id="chart_box">
                    <div id="chart_div"></div>
                </div>
            </div>
        </div>
    </div>

 </div>

</div>
@endsection