app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['domain' => 'cron.tibiacharts.com'], function()
{
    Route::get('/map', 'CronController@cronMap');
    Route::get('/houses', 'CronController@HouseCronJob');
});

Route::group(['middleware' => 'web', 'prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('setCookie', 'Controller@setCookie');
    Route::get('getCookie/{name}', 'Controller@getCookie');

    Route::get('/', 'HomeController@index');

    Route::get('/home', 'HomeController@index');

//    Route::get('/characters', 'PlayerController@indexPlayers');
//    Route::post('/characters', 'PlayerController@indexPlayers');
//
    Route::get('/logs', 'LogsSystemController@index');
    Route::post('/logs', 'LogsSystemController@store');
    Route::get('/log/{code}', 'LogsSystemController@indexLog');
//
//    Route::get('/events', 'EventController@index');

    Route::match(['get','post'], '/maps', 'HouseController@index');

    Route::match(['get','post'], '/houses', 'HouseController@index');
    Route::get('/getHouse', 'HouseController@getHouse');
    Route::get('/alertHouse', 'HouseController@alertHouse');
    Route::get('/listHouses', 'HouseController@listHouses');

    Route::match(['get', 'post'], '/npcs', 'NpcController@index');
    Route::get('/getNpc', 'NpcController@getNpc');
    Route::get('/listNpcs', 'NpcController@listNpcs');

    Route::match(['get','post'], '/hunts', 'HuntController@index');
    Route::get('/getHunt', 'HuntController@getHunt');
    Route::get('/listHunts', 'HuntController@listHunts');

    Route::match(['get','post'], '/races', 'RaceController@index');
    Route::match(['get','post'], '/bosses', 'RaceController@bosses');
    Route::get('/getRace', 'RaceController@getRace');
    Route::get('/listRaces', 'RaceController@listRaces');
    Route::get('/getKills', 'Races_killController@getKills');




    /* Route for Cronjobs */
    Route::group(['prefix'=>'cron'], function(){
        Route::get('/houses', 'HouseStatusController@cronHouses');
        Route::get('/auctionedHouses', 'HouseStatusController@cronHousesAuctioned');
        Route::get('/worlds', 'WorldController@cronWorld');
        Route::get('/npcs/{url?}', 'NpcController@cronNpc');
        Route::get('/races', 'RaceController@cronRacesWiki');
        Route::get('/normalraces', 'RaceController@getRacesContent');
        Route::get('/killstatistics', 'Races_killController@cronKillStatistics');
        Route::get('/itens/{url?}', 'ItenController@cronItens');

    });

    /* Route for ADMIN */
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){

        Route::get('', 'UserController@indexAdmin');

        Route::get('scripts/{tipo?}', 'ScriptsController@index');

        Route::get('crop', 'CropImageController@index');
        Route::post('crop', 'CropImageController@crop');

        Route::get('users', 'UserController@indexAdmin');
        Route::put('users', 'UserController@store');
        Route::patch('users', 'UserController@update');
        Route::delete('users', 'UserController@delete');

        Route::get('home', 'UserController@indexAdmin');

        Route::get('npcs', 'NpcController@indexAdmin');
        Route::get('getDataNpc', 'NpcController@getDataNpc');
        Route::put('npcs', 'NpcController@store');
        Route::patch('npcs', 'NpcController@update');


        Route::get('professions', 'ProfessionController@indexAdmin');
        Route::put('professions', 'ProfessionController@store');
        Route::patch('professions', 'ProfessionController@update');
        Route::delete('professions', 'ProfessionController@delete');
        Route::get('getDataProfession', 'NpcController@getDataProfession');


        Route::get('houses', 'HouseController@indexAdmin');
        Route::patch('houses', 'HouseController@update');

        Route::get('races', 'RaceController@indexAdmin');
        Route::put('races', 'RaceController@store');
        Route::patch('races', 'RaceController@update');
        Route::delete('races', 'RaceController@delete');

        Route::get('getRacesMap', 'Race_mapController@getRacesMap');
        Route::get('getRaceMap', 'Race_mapController@getRaceMap');

        Route::put('races_map', 'Race_mapController@store');
        Route::patch('races_map', 'Race_mapController@update');
        Route::delete('races_map', 'Race_mapController@delete');


        Route::get('hunts', 'HuntController@indexAdmin');
        Route::put('hunts', 'HuntController@store');
        Route::patch('hunts', 'HuntController@update');
        Route::delete('hunts', 'HuntController@delete');

        Route::get('getPlaces', 'Hunts_PlaceController@getPlaces');
        Route::get('getPlace', 'Hunts_PlaceController@getPlace');
        Route::get('getRaces', 'Hunts_PlaceController@getRaces');

        Route::put('places', 'Hunts_PlaceController@store');
        Route::patch('places', 'Hunts_PlaceController@update');
        Route::delete('places', 'Hunts_PlaceController@delete');

        Route::put('place_race', 'Place_RaceController@store');
        Route::delete('place_race', 'Place_RaceController@delete');

        Route::get('events', 'EventController@indexAdmin');
        Route::put('events', 'EventController@store');
        Route::patch('events', 'EventController@update');
        Route::delete('events', 'EventController@delete');

        Route::get('/map', 'MapController@indexAdmin');
        Route::post('/map', 'MapController@generate');

    });

    Route::auth();

});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    
    
    protected $fillable = ['name', 'date_start', 'date_end', 'description'];
    
    
    
    public function getDateStartFormatedAttribute()
    {
        $date = $this->attributes['date_start'];
        
        return implode('/',array_reverse(explode('/', $date))).'/'.date('Y');
    }
    
    
    public function getDateEndFormatedAttribute()
    {
        $date = $this->attributes['date_end'];
        return implode('/',array_reverse(explode('/', $date))).'/'.date('Y');
    }
    
    
    
    public function getDateStartIntAttribute()
    {
        $date = $this->attributes['date_start'];
        return $date.'/'.date('Y');
    }
    
    
    
    public function getDateEndIntAttribute()
    {
        $date = $this->attributes['date_end'];
        return $date.'/'.date('Y');
    }
    
    
    
    public function getColorAttribute()
    {
        return randColor($this->id);
        
    }
    
    
    public function getNameUrlAttribute()
    {
        return urlencode($this->name);
        
    }
    
    
    public function getNameHtmlAttribute()
    {
        return mb_convert_encoding($this->name, "UTF-8", "HTML-ENTITIES");
        
    }
}

app/LogsSystem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogsSystem extends Model
{
        
    public $table = 'logs_system';
    public $timestamps = false;
    
    protected $fillable = ['name', 'hunt', 'hits', 'exp', 'heal', 'itens_used', 'date', 'code', 'profit', 'waste'];
    
    
    
    public function player()
    {
        return $this->belongsTo(Player::class);
    }
    
    
    
    public function races()
    {
        return $this->hasMany(Races_loot::class);
    }
    
    
    
    public function getImagePathAttribute() 
    {
        
        $arrayImg = getImgs('creaures');
        
        return imgMatch($arrayImg, $this->attributes['name']);
    }
    
    
    
    public function getExpArrayAttribute()
    {
        $experiences = json_decode($this->attributes['exp']);
        foreach ($experiences as &$exp) {
            $exp *= 60;
        }
        return ($experiences);
    }
    
    
    
    public function getItensUsedAttribute()
    {
        $itens = $this->attributes['itens_used'];
        $ItensAux = explode(',',$itens);
        
        $arrayItens = getImgs('itens');
        
        $return = array();
        
        foreach ($ItensAux as $i=>$itemUsed) {
            
            $aux = explode(':',$itemUsed);
            $list = new \stdClass();
            
            $file = imgMatch($arrayItens, $aux[0]);

                if ($file) {
                    $list->img = '/images/itens/'.$file.'.gif';
                    $list->title = ucwords($aux[0]);
                    $list->label = $aux[1];
                }
            array_push($return, $list);
        }
        
        return $return;
    }
    
    
    
    public function getHuntAttribute()
    {
            
        $hunt = explode(',',$this->attributes['hunt']);
        
        $log = new \stdClass();
        $log->exp = $hunt[0];
        $log->time = $hunt[1];
        $log->perhour = $hunt[2];
        $log->perhour_int = str_replace('k','000',$hunt[2]);

        return $log;
        
    }
    
    
    
    public function getHitsAttribute()
    {

        $hits = explode(',',$this->attributes['hits']);
        
        $log = new \stdClass();
        $log->total = $hits[0];
        $log->dpt = $hits[3];
        $log->best = $hits[2];

        return $log;
        
    }
    
    
    
    public function getHealAttribute()
    {
        $heal = explode(',',$this->attributes['heal']);

        $log = new \stdClass();
        $log->total = round($heal[0]);
        $log->dpt = round($heal[2]);
        $log->best = round($heal[1]);

        return $log;
        
    }
    
    
    
    public function getProfitAttribute()
    {
        $hunt = explode(',',$this->attributes['hunt']);
            
        $totalTime = explode(" h",trim($hunt[1]," min"));

        $minTotal = ($totalTime[0]*60)+($totalTime[1]);
        
        $media = $this->attributes['profit']/$minTotal;

        $result = $media*60;
        
        $log = new \stdClass();
        $log->profitPerhour = round($result);

        $log->total = number_format(($this->attributes['profit']-$this->attributes['waste']), 0, ',','.');
        $log->profit_noformat = $this->attributes['profit'];
        $log->profit = number_format($this->attributes['profit'], 0, ',','.');
        $log->waste = number_format($this->attributes['waste'], 0, ',','.');

        return $log;
        
    }
    
    
    
    
}

app/Npc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Npc extends Model
{    
    
    public static $url = 'Lista_de_NPCs_por_Localiza%C3%A7%C3%A3o';
    public static $urlBase = 'http://www.tibiawiki.com.br/wiki/';
    
    protected $fillable = ['name', 'town_id', 'coord', 'floor', 'observation', 'profession_id'];
    public $timestamps = false;
    
    
    public function town() 
    {
        return $this->belongsTo(Town::class);
    }

    
    
    public function profession() 
    {
        return $this->belongsTo(Profession::class);
    }
    
    
    
    public function getRealFloorAttribute() 
    { 
        return (($this->attributes['floor'] -7) * (-1));
    }
    
    
    
    public function getImagePathAttribute() 
    {
        if (empty($arrayImg)) {
            $arrayImg = getImgs('npcs');
        }
        $path = '/images/npcs/'.imgMatch($arrayImg, $this->attributes['name']).'.gif';
        
        return $path;
    }
    
    
    
    public function getNameDecodedAttribute()
    {
        return str_replace("'","&apos;",$this->attributes['name']);
    }
    
    
    
    public function getNameUrlAttribute()
    {
        return str_replace(" ","_",$this->attributes['name']);
    }
    
    
    
     public function getCoordXAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[0]+1005);
        
    }
    
    
    
    public function getObservationTransAttribute()
    {
        $locale = \App::getLocale();
        
        $text = $this->attributes['observation'];

        preg_match('/\<'.$locale.'>(?P<translated>.*)\<\/'.$locale.'\>/', $text, $match);
        
        if (!empty($match['translated'])) {
            return ($match['translated']);
        } else {
            return '';
        }

        
    }
    
    
    
    public function getCoordYAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[1]+1025);
        
    }
    
    
    /* script to capture npcs from tibiawiki */
    public static function getNpcsContent() 
    {

        $npcArray = array();
        $arrayTd = array();
        
        $tables = getData(self::$urlBase . self::$url,'','.sortable');

        $line = 1;
        foreach($tables['tr>td'] as $tr) {

            $td = $tr->nodeValue;
        
            $find = array('/\s+\s+/', '/\n/');
            $replace = array('\s+', '');
            $arrayTd[$line] = preg_replace($find, $replace, $td);
            
            if ($line==5) {
                array_push($npcArray, $arrayTd);
                
                $line = 1;
                $arrayTd = array();
            } else {
                $line++;
            }
            
         }

        return $npcArray;

    }
 
}

app/PlayersLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class PlayersLog extends Model
{
    
    
    protected $dates = ['date'];
    protected $table = 'players_log';
    public $dateStart = '';
    public $dateEnd = '';
    
    
    
    public function __construct()
    {
        $this->dateStart = date('Y-m-d', strtotime('-6 days'));
        $this->dateEnd = date('Y-m-d');
        
    }
    
    
    
    public function player()
    {
        return $this->belongsTo(Player::class, 'idplayer');
    }
    
    
    
    public function getDateJsAttribute()
    {
        return datePHPtoJS($this->attributes['date'], 'year');
    }
    
    
    public function getHourJsAttribute()
    {
        return datePHPtoJS($this->attributes['date']);
    }
    

}

resources/views/principal/pages/events.blade.php
@extends('layouts/default')

@section('title')
Eventos
@endsection

@section('cssfile')
<link rel="stylesheet" href="/plugins/fullcalendar/fullcalendar.min.css">
<link rel="stylesheet" href="/plugins/fullcalendar/fullcalendar.print.css" media="print">
@endsection

@section('content')
<div class="row">
    <div class="box box-primary">
        <div class="box-body no-padding">
            <!-- THE CALENDAR -->
            <div id="calendar"></div>
        </div>
    <!-- /.box-body -->
    </div>
</div>
@endsection

@section('jsfile')
<!-- fullCalendar 2.2.5-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="/plugins/fullcalendar/fullcalendar.min.js"></script>

<script>
/* initialize the calendar
     -----------------------------------------------------------------*/
    //Date for the calendar events (dummy data)
    var date = new Date();
    var d = date.getDate(),
        m = date.getMonth(),
        y = date.getFullYear();

    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
      },
      buttonText: {
        today: 'today',
      },
      //Random default events
      events: [
      @foreach ($events as $event)
        {
          title: "{{ $event->name_html }}",
          start: "{{ $event->date_start_int }}",
          end: '{{ $event->date_end_int }}',
          url: 'http://www.tibia.com/library/?subtopic=worldquests&page=details&worldquest={{ $event->name_url }}',
          backgroundColor: "{{ $event->color }}",
          borderColor: "{{ $event->color }}"
        },
      @endforeach
      ],
      editable: false,
      droppable: false, // this allows things to be dropped onto the calendar !!!
    });    
</script>
@endsection

resources/views/principal/pages/houses.blade.php
@extends('principal.skell')

@push('title')
@lang('texts.houses_guildhalls')
@endpush

@push('styles')
<link href="/css/houses.css?version={{ rand(10,99) }}" rel="stylesheet">
@endpush
@section('content')
<h1>@yield('title')</h1>
<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.town')</div>
            <div class="panel-body">
                <form id="form" class="box" method="post">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="box-body">

                            <div class="form-group">
                                <label>@lang('texts.select_town')</label>
                                <select class="form-control" id="idwtown" name="town_id">
                                    <option value="">@lang('texts.all')</option>
                                    @foreach ($towns as $town)
                                    <option value="{{ $town->id }}" @if (!empty($request->input('town_id') && $request->input('town_id') == $town->id)) selected @endif>{{ $town->name }}</option>
                                    @endforeach
                                </select>
                            </div>


                    </div>

                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.legends')</div>

            <div class="panel-body">
                <label>@lang('texts.select_type')</label>

                <div class="btn btn-block btn-danger col-lg-4 col-sm-12 margin-bottom listHouse" data-status="rented">
                    @lang('texts.rented')
                </div>

                <div class="btn btn-block btn-warning col-lg-4 col-sm-12 margin-bottom listHouse" data-status="bided">
                    @lang('texts.active_bid')
                </div>

                <div class="btn btn-block btn-success col-lg-4 col-sm-12 margin-bottom listHouse" data-status="auctioned">
                    @lang('texts.no_bid')
                <input type="hidden" value="" id="housesstatus">
                </div>
              </div>
        </div>
      </div>
</div>
<div class="row" id="showMap">
  <div class="col-sm-12">
    <div class="panel panel-primary">
        <div class="panel-heading">{{ $world->name }}</div>
        <div class="panel-body">
                <div id="tibia_map"></div>
                <div id="map_info" class="bg-gray">
                    <div  id="info_coords" onclick="SelectElement('info_coords');"></div>

                </div>

        </div>
    </div>

   </div>
</div>

<div id="showHouses">

</div>

<div class="modal fade" id="infobox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content" enctype="multipart/form-data" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">@lang('texts.houses_guildhalls')</h4>

            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">@lang('texts.close')</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

<script src="/js/houses.js?version={{ rand(10,99) }}"></script>
<script src="/js/maps.js?version={{ rand(10,99) }}"></script>

@if(!empty($status))
<script type="text/javascript">
@foreach ($status as $i=>$house)
    houses[{{ $i }}] = {id:'{{ $house->house->id }}', name:'{{ $house->house->name_decoded }}',color:'{{ $house->color }}',coord:[{{ $house->house->coord }}],floor:{{ $house->house->floor }}};
@endforeach

@if(!empty($town_zoom))

floor = {{ $town_zoom->floor }};
start_x = {{ $town_zoom->coord_x }};
start_y = {{ $town_zoom->coord_y }};
start_zoom = 4;
@endif

</script>
@endif

@endpush

resources/views/principal/pages/hunts.blade.php
@extends('layouts.block')

@push('title')
@lang('texts.hunts')
@endpush

@push('styles')
<link href="/css/hunts.css?version={{ rand(10,99) }}" rel="stylesheet">
@endpush
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="dash-unit">
            <dtitle>@lang('texts.hunts')</dtitle>
            <hr>
            <form id="form" class="box" method="post">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="box-body">

                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="form-group">
                            <label>@lang('texts.select_race'):</label>
                            <select class="form-control listHunts" name="id">
                                <option value="">@lang('texts.all')</option>
                                @foreach ($races as $k=>$race) {
                                    <option value="{{ $race->id }}" @if (!empty($request->input('id') && $request->input('id') == $race->id)) selected @endif>{{ $race->name }}</option>';
                                @endforeach
                            </select>
                          </div>

                    </div>
                    <div class='clearfix'></div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">@lang('texts.search')</button>
                    </div>

                </div>
            </form>

        </div>
    </div>
</div>
<div class="row" id="showMap">
    <div class="col-md-12">
        <div class="dash-unit">
            <dtitle>@lang('texts.map')</dtitle>
            <hr>
            <div class="box col-md-12">
                <div id="tibia_map"></div>
                <div id="map_info" class="bg-gray">
                    <div  id="info_coords" onclick="SelectElement('info_coords');"></div>
                    <small>Original Code by Aissy of tibialibrary.</small>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="showHunts">

</div>
<div class="modal fade" id="infobox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content formNew" enctype="multipart/form-data" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">@lang('texts.hunts')</h4>

            </div>
            <div class="modal-body col-md-12">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">@lang('texts.close')</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

<script src="/js/hunts.js?version={{ rand(10,99) }}"></script>
<script src="/js/maps.js?version={{ rand(10,99) }}"></script>


@if(!empty($places))
<script type="text/javascript">
SetSize();

@if (!empty($places))
  @foreach ($places as $i=>$place)
    @if ($place->coord)
        hunts[{{ $i }}] = {id: {{ $place->id }}, name:"{{ $place->hunt->name }}", color:"{{ $place->color }}", radius:"{{ $place->size }}", coord:[{{ $place->coord }}], floor:{{ $place->floor }} };
    @endif
  @endforeach
@endif

//@if(!empty($town_zoom))
//    floor = {{ $town->floor }};
//    start_x = {{ $town->coord_x }};
//    start_y = {{ $town->coord_y }};
//    start_zoom = 4;
// @endif

//@if(!empty($hunt_zoom))
//floor = {{ $hunt_zoom->floor }};
//start_x = {{ $hunt_zoom->coord_x }};
//start_y = {{ $hunt_zoom->coord_y }};
//start_zoom = 5;
//@endif
</script>
@endif

@endpush

resources/views/principal/pages/npcs.blade.php
@extends('principal.skell')

@push('title')
@lang('texts.npcs')
@endpush

@push('styles')
<link href="/css/npcs.css?version={{ rand(10,99) }}" rel="stylesheet">
@endpush
@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.npcs')</div>
            <div class="panel-body">
                      <label>@lang('texts.select_npc'):</label>
                      <input type="text" id="tags" class="form-control">
                      <div id="containerTag"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">@lang('texts.profession')</div>
            <div class="panel-body">
                <form id="form" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <label>@lang('texts.select_profession'):</label>

                    <select class="form-control" id="profession" name="profession">
                        <option value="">@lang('texts.all')</option>
                        @foreach ($professions as $k=>$profession) {
                            <option value="{{ $profession->id }}" @if (!empty($request->input('id') && $request->input('id') == $profession->id)) selected @endif >{{ $profession->profession_trans }}</option>
                        @endforeach
                    </select>

                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="showMap">
  <div class="col-sm-12">
    <div class="panel panel-primary">
        <div class="panel-heading">Map</div>
        <div class="panel-body">
            <div id="tibia_map"></div>
            <div id="map_info" class="bg-gray">
                <div  id="info_coords" onclick="SelectElement('info_coords');"></div>
            </div>
        </div>
    </div>
  </div>
</div>

<div id="showNpcs">

</div>

<div class="modal fade" id="infobox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content formNew" enctype="multipart/form-data" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Npc</h4>

            </div>
            <div class="modal-body col-md-12">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">@lang('texts.close')</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="/js/npcs.js?version={{ rand(10,99) }}"></script>
<script src="/js/maps.js?version={{ rand(10,99) }}"></script>


@if(!empty($npcs))
<script type="text/javascript">
SetSize();
var npcsName = [];

@foreach ($npcs as $i=>$npc)
    npcs[{{ $i }}] = {id: {{ $npc->id }}, name: "{{ $npc->name_decoded }}", img: "{{ $npc->image_path }}", coord:[{{ $npc->coord }}], floor:{{ $npc->floor }} };
    npcsName[{{ $i }}] = {value: {{ $npc->id }}, label:"{{ $npc->name_decoded }}", coord_x: {{ $npc->coord_x }}, coord_y: {{ $npc->coord_y }}, floor:{{ $npc->floor }} };
@endforeach

@if(!empty($town_zoom))
    floor = {{ $town->floor }};
    start_x = {{ $town->coord_x }};
    start_y = {{ $town->coord_y }};
    start_zoom = 4;
 @endif


</script>
@endif

@endpush

resources/views/principal/pages/races.blade.php
@extends('principal.skell')

@push('title')
@lang('texts.npcs')
@endpush

@push('styles')
<link href="/css/races.css?version={{ rand(10,99) }}" rel="stylesheet">
@endpush
@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
          <div class="panel-heading">@lang('texts.races')</div>
          <div class="panel-body">
              <form id="form" class="box" method="post">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="box-body">

                  <div class="col-md-4 col-sm-6 col-xs-12">
                      <div class="form-group">
                          <label>@lang('texts.select_race'):</label>
                          <select class="form-control listRaces" name="id">
                              <option value="">@lang('texts.all')</option>

                              @foreach ($races as $k=>$race) {
                                  <option value="{{ $race->id }}" @if (!empty($request->input('id') && $request->input('id') == $race->id)) selected @endif>{{ $race->name }}</option>';
                              @endforeach
                          </select>
                        </div>
                        <div class='clearfix'></div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">@lang('texts.search')</button>
                        </div>
                  </div>

                </div>
            </form>
          </div>
      </div>
    </div>
</div>

<div class="row" id="showMap">
  <div class="col-sm-12">
    <div class="panel panel-primary">
        <div class="panel-heading">Map</div>
        <div class="panel-body">
            <div id="tibia_map"></div>
            <div id="map_info" class="bg-gray">
                <div  id="info_coords" onclick="SelectElement('info_coords');"></div>
            </div>
        </div>
    </div>
  </div>
</div>

<div id="showRaces">

</div>

<div class="modal fade" id="infobox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content formNew" enctype="multipart/form-data" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">@lang('texts.races')</h4>

            </div>
            <div class="modal-body col-md-12">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">@lang('texts.close')</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="/js/races.js?version={{ rand(10,99) }}"></script>
<script src="/js/maps.js?version={{ rand(10,99) }}"></script>


@if(!empty($places))
<script type="text/javascript">
SetSize();
@if (!empty($races))
  @foreach ($races as $i=>$race)
    @if ($race->coords)
        races.push({id: {{ $race->id }}, name:"{{ $race->name }}", img: "{{ $race->image_path }}", coord:[{!! ($race->coords) !!}] });
    @endif
  @endforeach
@endif


</script>
@endif

@endpush