app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['domain' => 'cron.tibiacharts.com'], function()
{
    Route::get('/map', 'CronController@cronMap');
    Route::get('/houses', 'CronController@HouseCronJob');
});

Route::group(['middleware' => 'web', 'prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('setCookie', 'Controller@setCookie');
    Route::get('getCookie/{name}', 'Controller@getCookie');

    Route::get('/', 'HomeController@index');

    Route::get('/home', 'HomeController@index');

//    Route::get('/characters', 'PlayerController@indexPlayers');
//    Route::post('/characters', 'PlayerController@indexPlayers');
//
    Route::get('/logs', 'LogsSystemController@index');
    Route::post('/logs', 'LogsSystemController@store');
    Route::get('/log/{code}', 'LogsSystemController@indexLog');
//
//    Route::get('/events', 'EventController@index');

    Route::match(['get','post'], '/maps', 'HouseController@index');

    Route::match(['get','post'], '/houses', 'HouseController@index');
    Route::get('/getHouse', 'HouseController@getHouse');
    Route::get('/alertHouse', 'HouseController@alertHouse');
    Route::get('/listHouses', 'HouseController@listHouses');

    Route::match(['get', 'post'], '/npcs', 'NpcController@index');
    Route::get('/getNpc', 'NpcController@getNpc');
    Route::get('/listNpcs', 'NpcController@listNpcs');

    Route::match(['get','post'], '/hunts', 'HuntController@index');
    Route::get('/getHunt', 'HuntController@getHunt');
    Route::get('/listHunts', 'HuntController@listHunts');

    Route::match(['get','post'], '/races', 'RaceController@index');
    Route::match(['get','post'], '/bosses', 'RaceController@bosses');
    Route::get('/getRace', 'RaceController@getRace');
    Route::get('/listRaces', 'RaceController@listRaces');
    Route::get('/getKills', 'Races_killController@getKills');




    /* Route for Cronjobs */
    Route::group(['prefix'=>'cron'], function(){
        Route::get('/houses', 'HouseStatusController@cronHouses');
        Route::get('/auctionedHouses', 'HouseStatusController@cronHousesAuctioned');
        Route::get('/worlds', 'WorldController@cronWorld');
        Route::get('/npcs/{url?}', 'NpcController@cronNpc');
        Route::get('/races', 'RaceController@cronRacesWiki');
        Route::get('/normalraces', 'RaceController@getRacesContent');
        Route::get('/killstatistics', 'Races_killController@cronKillStatistics');
        Route::get('/itens/{url?}', 'ItenController@cronItens');

    });

    /* Route for ADMIN */
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){

        Route::get('', 'UserController@indexAdmin');

        Route::get('scripts/{tipo?}', 'ScriptsController@index');

        Route::get('crop', 'CropImageController@index');
        Route::post('crop', 'CropImageController@crop');

        Route::get('users', 'UserController@indexAdmin');
        Route::put('users', 'UserController@store');
        Route::patch('users', 'UserController@update');
        Route::delete('users', 'UserController@delete');

        Route::get('home', 'UserController@indexAdmin');

        Route::get('npcs', 'NpcController@indexAdmin');
        Route::get('getDataNpc', 'NpcController@getDataNpc');
        Route::put('npcs', 'NpcController@store');
        Route::patch('npcs', 'NpcController@update');


        Route::get('professions', 'ProfessionController@indexAdmin');
        Route::put('professions', 'ProfessionController@store');
        Route::patch('professions', 'ProfessionController@update');
        Route::delete('professions', 'ProfessionController@delete');
        Route::get('getDataProfession', 'NpcController@getDataProfession');


        Route::get('houses', 'HouseController@indexAdmin');
        Route::patch('houses', 'HouseController@update');

        Route::get('races', 'RaceController@indexAdmin');
        Route::put('races', 'RaceController@store');
        Route::patch('races', 'RaceController@update');
        Route::delete('races', 'RaceController@delete');

        Route::get('getRacesMap', 'Race_mapController@getRacesMap');
        Route::get('getRaceMap', 'Race_mapController@getRaceMap');

        Route::put('races_map', 'Race_mapController@store');
        Route::patch('races_map', 'Race_mapController@update');
        Route::delete('races_map', 'Race_mapController@delete');


        Route::get('hunts', 'HuntController@indexAdmin');
        Route::put('hunts', 'HuntController@store');
        Route::patch('hunts', 'HuntController@update');
        Route::delete('hunts', 'HuntController@delete');

        Route::get('getPlaces', 'Hunts_PlaceController@getPlaces');
        Route::get('getPlace', 'Hunts_PlaceController@getPlace');
        Route::get('getRaces', 'Hunts_PlaceController@getRaces');

        Route::put('places', 'Hunts_PlaceController@store');
        Route::patch('places', 'Hunts_PlaceController@update');
        Route::delete('places', 'Hunts_PlaceController@delete');

        Route::put('place_race', 'Place_RaceController@store');
        Route::delete('place_race', 'Place_RaceController@delete');

        Route::get('events', 'EventController@indexAdmin');
        Route::put('events', 'EventController@store');
        Route::patch('events', 'EventController@update');
        Route::delete('events', 'EventController@delete');

        Route::get('/map', 'MapController@indexAdmin');
        Route::post('/map', 'MapController@generate');

    });

    Route::auth();

});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    
    
    protected $fillable = ['name', 'date_start', 'date_end', 'description'];
    
    
    
    public function getDateStartFormatedAttribute()
    {
        $date = $this->attributes['date_start'];
        
        return implode('/',array_reverse(explode('/', $date))).'/'.date('Y');
    }
    
    
    public function getDateEndFormatedAttribute()
    {
        $date = $this->attributes['date_end'];
        return implode('/',array_reverse(explode('/', $date))).'/'.date('Y');
    }
    
    
    
    public function getDateStartIntAttribute()
    {
        $date = $this->attributes['date_start'];
        return $date.'/'.date('Y');
    }
    
    
    
    public function getDateEndIntAttribute()
    {
        $date = $this->attributes['date_end'];
        return $date.'/'.date('Y');
    }
    
    
    
    public function getColorAttribute()
    {
        return randColor($this->id);
        
    }
    
    
    public function getNameUrlAttribute()
    {
        return urlencode($this->name);
        
    }
    
    
    public function getNameHtmlAttribute()
    {
        return mb_convert_encoding($this->name, "UTF-8", "HTML-ENTITIES");
        
    }
}

app/House.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class House extends Model
{

    protected $fillable = ['coord', 'floor', 'town_id'];
    public $timestamps = false;


    public function town()
    {
        return $this->belongsTo(Town::class);
    }



    public function status()
    {
        return $this->hasMany(HouseStatus::class);
    }



    public function alert()
    {
        return $this->hasMany(UserHouseAlert::class);
    }



    public function getRealFloorAttribute()
    {
        return (($this->attributes['floor'] -7) * (-1));
    }



    public function getCoordXAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        $center = ($coords[0]+$coords[2])/2;
        return $center;

    }



    public function getCoordYAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        $center = ($coords[1]+$coords[3])/2;
        return $center;
    }



    public function getNameDecodedAttribute()
    {
        return urlencode($this->attributes['name']);
    }



    public function getNameUtf8Attribute()
    {
        return str_replace("&nbsp;"," ",htmlentities($this->attributes['name'], ENT_QUOTES, "UTF-8"));
    }


    public function getTypeAttribute()
    {
        return ucfirst($this->attributes['type']);
    }



    public function getCoordAuxAttribute()
    {
        if ($this->attributes['coord'] == '') {
            $town = Town::where('id',$this->attributes['town_id'])->first();
            return $town->coord;
        }
    }

}

app/Npc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Npc extends Model
{    
    
    public static $url = 'Lista_de_NPCs_por_Localiza%C3%A7%C3%A3o';
    public static $urlBase = 'http://www.tibiawiki.com.br/wiki/';
    
    protected $fillable = ['name', 'town_id', 'coord', 'floor', 'observation', 'profession_id'];
    public $timestamps = false;
    
    
    public function town() 
    {
        return $this->belongsTo(Town::class);
    }

    
    
    public function profession() 
    {
        return $this->belongsTo(Profession::class);
    }
    
    
    
    public function getRealFloorAttribute() 
    { 
        return (($this->attributes['floor'] -7) * (-1));
    }
    
    
    
    public function getImagePathAttribute() 
    {
        if (empty($arrayImg)) {
            $arrayImg = getImgs('npcs');
        }
        $path = '/images/npcs/'.imgMatch($arrayImg, $this->attributes['name']).'.gif';
        
        return $path;
    }
    
    
    
    public function getNameDecodedAttribute()
    {
        return str_replace("'","&apos;",$this->attributes['name']);
    }
    
    
    
    public function getNameUrlAttribute()
    {
        return str_replace(" ","_",$this->attributes['name']);
    }
    
    
    
     public function getCoordXAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[0]+1005);
        
    }
    
    
    
    public function getObservationTransAttribute()
    {
        $locale = \App::getLocale();
        
        $text = $this->attributes['observation'];

        preg_match('/\<'.$locale.'>(?P<translated>.*)\<\/'.$locale.'\>/', $text, $match);
        
        if (!empty($match['translated'])) {
            return ($match['translated']);
        } else {
            return '';
        }

        
    }
    
    
    
    public function getCoordYAttribute()
    {
        $coords = explode(',',$this->attributes['coord']);
        return ($coords[1]+1025);
        
    }
    
    
    /* script to capture npcs from tibiawiki */
    public static function getNpcsContent() 
    {

        $npcArray = array();
        $arrayTd = array();
        
        $tables = getData(self::$urlBase . self::$url,'','.sortable');

        $line = 1;
        foreach($tables['tr>td'] as $tr) {

            $td = $tr->nodeValue;
        
            $find = array('/\s+\s+/', '/\n/');
            $replace = array('\s+', '');
            $arrayTd[$line] = preg_replace($find, $replace, $td);
            
            if ($line==5) {
                array_push($npcArray, $arrayTd);
                
                $line = 1;
                $arrayTd = array();
            } else {
                $line++;
            }
            
         }

        return $npcArray;

    }
 
}

app/Race.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Race extends Model
{
    protected $arrayImg;
    public static $url = 'Lista_de_Criaturas';
    public static $urlBase = 'http://www.tibiawiki.com.br/wiki/';
    protected $fillable = ['name', 'type', 'coords', 'hp', 'exp'];
    public $timestamps = false;



    public function places() {

        return $this->belongsToMany(Place_Race::class, 'places_races', 'race_id', 'place_id');
    }



    public function loots() {

        return $this->hasMany(Races_loot::class,'race_id');
    }



    public function getImagePathAttribute() {

        if (empty($this->arrayImg)) {
            $this->arrayImg = getImgs('creatures');
        }

        $path = '/images/creatures/'.imgMatch($this->arrayImg, $this->attributes['name']).'.gif';

        return $path;
    }



    public function getNameUrlAttribute()
    {
        return str_replace(" ","_",$this->attributes['name']);
    }



    public function getHpNumberAttribute()
    {
        $hp = number_format($this->attributes['hp'], 0, ',', '.');

        return $hp;
    }



    public function getExpNumberAttribute()
    {
        $exp = number_format($this->attributes['exp'], 0, ',', '.');

        return $exp;
    }



    public function getTypeNameAttribute()
    {
        if ($this->attributes['type'] == 1) {
          return 'Boss';
        }

    }



    function getCoordsObjAttribute() {

        $arr_coord = '['.$this->attributes['coords'].']';
        $coords = json_decode($arr_coord);

        foreach ($coords as &$coord) {
            $coord->x += 1005;
            $coord->y += 1025;
        }

        return $coords;

    }



    /* script to capture npcs from tibiawiki */
    public static function getRaceListContentWiki()
    {

        $raceArray = array();
        $arrayTd = array();

        $tables = getData(self::$urlBase.self::$url);

        $line = 1;
        $start = false;
        foreach($tables['tr>td'] as $tr) {

            $td = $tr->nodeValue;

            $tdx = preg_replace('/\s+/', ' ', $td);

                $arrayTd[$line] = $tdx;

                if ($line=='7') {
                    array_push($raceArray, $arrayTd);

                    $line = 1;
                    $arrayTd = array();
                } else {
                    $line++;
                }

         }

        return $raceArray;

    }



    /* script to capture information of especific race from tibiawiki */
    public static function getRaceContentWiki($url)
    {

        $raceArray = array();
        $arrayTd = array();

        $tables = getData(self::$urlBase.$url);

        foreach($tables['tr>td'] as $tr) {

            $td = $tr->nodeValue;

            $tdx = preg_replace('/\s+/', ' ', $td);

            return $tdx;

         }


    }



    static public function getRaceListContentTibia()
    {

    		$tables = getData(self::$urlBase.self::$url, '', 'div');

    		$racesArray = array();

        // dd($tables->nodeValue);

    		foreach($tables['div'] as $tr) {

    						$td = preg_split('/&nbsp;/', htmlentities($tr->nodeValue), 0, PREG_SPLIT_NO_EMPTY);

    						if (!empty($td)) {

    							array_push($racesArray, str_replace('&Acirc;','',$td));
    						}


    		}

    		return $racesArray;

    }
}

resources/views/admin/pages/crop.blade.php
@extends('admin.layouts.default')

@section('includes')

@stop

@section('content')
<div class="row">
    
    <div class="col-md-12">
       <div class="panel panel-default">
           
           <div class="panel-body">
               <form method="post" action="crop">
                   <input type="hidden" name="_token" value="{{ csrf_token() }}">
                   <div class="col-md-4">
                        <label>Location Source:</label>
                        <input type="text" name="locationFrom">
                   </div>
                   <div class="col-md-4">
                        <label>Location To:</label>
                        <input type="text" name="locationTo">
                   </div>
                   <div class="col-md-4">
                        <label>Name:</label>
                        <input type="text" name="name">
                   </div>
                   <button type="submit" class="btn btn-primary">GO</button>
               </form>
           </div>
 
           
       </div>

   </div>
</div>
@stop

resources/views/admin/pages/home.blade.php
@extends('admin.layouts.default')

@section('content')
<h1> Admin Home </h1>
@stop

resources/views/admin/pages/npcs.blade.php
@extends('admin.layouts.default')

@section('includes')
<link href="{{ asset('/css/npcs.css') }}" rel="stylesheet" />
<script src="{{ asset('/js/admin.npcs.js') }}" type="text/javascript" ></script>
@stop

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <button class="btn btn-primary btn-lg cleanForm newNpc" data-toggle="modal" data-target="#formNpc">
                    Novo
                 </button>
            </div>
        </div>
    </div>
    <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-heading">
               Npcs
           </div>
           <div class="panel-body">
               <div class='table-responsive'>
                   <table id="tableNpcs" class="table table-responsive">
                       <thead>
                           <tr>
                               <th>#</th>
                               <th width="10%">Image</th>
                               <th>Name</th>
                               <th>Coord</th>
                               <th>Floor</th>
                               <th>Town</th>
                               <th>Action</th>
                               <th>Wiki</th>
                           </tr>
                       </thead>
                       <tbody>
                       @foreach ($npcs as $npc)
                           <tr>
                                <td>{{ $npc->id }}</td>
                                <td align="center"><img src="{{ $npc->image_path }}"></td>
                                <td>{{ $npc->name }}</td>
                                <td>{{ $npc->coord }}</td>
                                <td>{{ $npc->real_floor }}</td>
                                <td>{{ $npc->town->name }}</td>
                                <td><button class="btn btn-primary col-md-12 editNpc"  data-toggle="modal" data-target="#formNpc">
                                       <i class="fa fa-edit"></i> Edit
                                       <input type="hidden" class="getIdNpc" value="{{ $npc->id }}">
                                       <input type="hidden" class="getName" value="{{ $npc->name }}">
                                       <input type="hidden" class="getCoord" value="{{ $npc->coord }}">
                                       <input type="hidden" class="getTown" value="{{ $npc->town->id }}">
                                       <input type="hidden" class="getProfession" value="{{ $npc->profession->id }}">
                                       <input type="hidden" class="getObservation" value="{{ $npc->observation }}">

                                   </button>
                                </td>
                                <td align="center"><a href="http://tibiawiki.com.br/wiki/{{ $npc->name_url }}" target="_blank">Wiki</a></td>
                           </tr>
                       @endforeach
                       </tbody>
                       <tfoot>
                           <tr>
                               <th>#</th>
                               <th>Image</th>
                               <th>Name</th>
                               <th>Coord</th>
                               <th>Floor</th>
                               <th>Town</th>
                               <th>Action</th>
                               <th>Wiki</th>
                           </tr>
                       </tfoot>
                   </table>
               </div>
           </div>
       </div>
        <div class="col-md-8 col-md-offset-4">
        {!! $npcs->render() !!}
        </div>
   </div>
</div>

<div class="modal fade" id="formNpc" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <form class="modal-content formNpc" action="/admin/npcs" method="POST">
            <input type="hidden" name="_method" id="method" value="PUT"></span>
            {!! csrf_field() !!}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"></h4>

            </div>
            <div class="modal-body col-md-12">
                <div class="form-group col-md-6 col-xs-12">
                    <label for="npcName">Name</label>
                    <input type="text" class="form-control" id="npcName" professionholder="Enter name" name="name" />
                </div>
               <div class="form-group col-md-6 col-xs-12">
                    <label for="npcCoord">Coord</label>
                    <input type="text" id="npcCoord" class="form-control coordenadas" professionholder="Enter Coords" name="coord" />
                </div>
                <div class="form-group col-md-6 col-xs-12">
                    <label for="npcFloor">Floor</label>
                    <select class="form-control floor" id="npcFloor" name="floor">
                        <option value="0">7</option>
                        <option value="1">6</option>
                        <option value="2">5</option>
                        <option value="3">4</option>
                        <option value="4">3</option>
                        <option value="5">2</option>
                        <option value="6">1</option>
                        <option value="7">0</option>
                        <option value="8">-1</option>
                        <option value="9">-2</option>
                        <option value="10">-3</option>
                        <option value="11">-4</option>
                        <option value="12">-5</option>
                        <option value="13">-6</option>
                        <option value="14">-7</option>
                        <option value="15">-8</option>
                    </select>
                </div>

                <div class="form-group col-md-6 col-xs-12">
                    <label>Town</label>
                    <select class="form-control" id="npcTown" name="town_id">
                        @foreach ($towns as $town)
                        <option value='{{ $town->id }}'>{{ $town->name }}</option>
                       @endforeach
                    </select>
                </div>

                <div class="form-group col-md-6 col-xs-12">
                    <label>Profession</label>
                    <select class="form-control" id="npcProfession" name="profession_id">
                        @foreach ($professions as $profession)
                        <option value='{{ $profession->id }}'>{{ $profession->profession_trans }}</option>
                       @endforeach
                    </select>
                </div>

                <div class="form-group col-md-12">
                    <label for="npcObservation">Observation</label>
                    <textarea type="text" class="form-control" id="npcObservation" name="observation" ></textarea>
                </div>

                <div class="form-group col-md-12 col-xs-12 setMap">
                    <iframe src="/map.html" width="540" height="350"></iframe>
                </div>

            </div>
            <div class="modal-footer">
                <input type="hidden" id="npcId" name="id" value="">
                <input type="hidden" id="typeMap" value="icon">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </form>
    </div>
</div>

@stop

resources/views/admin/pages/races.blade.php
@extends('admin.layouts.default')

@section('includes')
<link href="{{ asset('/css/races.css') }}" rel="stylesheet" />
<script src="{{ asset('/js/admin.races.js') }}" type="text/javascript" ></script>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <button class="btn btn-primary btn-lg cleanForm newRace" data-toggle="modal" data-target="#formRace">
                    Novo
                 </button>
            </div>
        </div>
    </div>
    <div class="col-md-12">
       <div class="panel panel-default">
           <div class="panel-heading">
               Races
           </div>
           <div class="panel-body">
               <div class='table-responsive'>
                   <table id="tableRaces2" class="table table-responsive">
                       <thead>
                           <tr>
                               <th width="1%">#</th>
                               <th width="1%">Image</th>
                               <th width="20%">Name</th>
                               <th>Type</th>
                               <th width="20%">Coords</th>
                               <th>Action</th>
                               <th></th>
                           </tr>
                       </thead>
                       <tbody>
                       @foreach ($races as $race)
                           <tr>
                               <td>{{ $race->id }}</td>
                               <td><img src="{{ $race->image_path }}"></td>
                               <td>{{ $race->name }}</td>
                               <td>{{ $race->type_name }}</td>
                               <td>{{ $race->coords }}</td>
                               <td><button class="btn btn-primary col-md-2 col-xs-6 editRace"  data-toggle="modal" data-target="#formRace">
                                      <i class="fa fa-edit"></i> Edit
                                      <input type="hidden" class="getIdRace" value="{{ $race->id }}">
                                      <input type="hidden" class="getName" value="{{ $race->name }}">
                                      <input type="hidden" class="getType" value="{{ $race->type }}">
                                      <input type="hidden" class="getHp" value="{{ $race->hp }}">
                                      <input type="hidden" class="getExp" value="{{ $race->exp }}">
                                      <input type="hidden" class="getCoords" value="{{ $race->coords }}">
                                  </button>
                                  <form class="col-md-2 col-xs-6" action="/admin/races" method="POST" id="formDelete">
                                      <button class="btn btn-danger deleteRace"><i class="fa fa-trash"></i> Delete</button>
                                      <input type="hidden" name="id" value="{{ $race->id }}">
                                      {{ method_field('DELETE')}}
                                       {!! csrf_field() !!}
                                  </form>

                               </td>
                               <td align="center"><a href="http://tibiawiki.com.br/wiki/{{ $race->name_url }}" target="_blank">Wiki</a></td>
                           </tr>
                       @endforeach
                       </tbody>
                       <tfoot>
                           <tr>
                               <th>#</th>
                               <th>Image</th>
                               <th>Name</th>
                               <th>Type</th>
                               <th>Coords</th>
                               <th>Action</th>
                               <th></th>
                           </tr>
                       </tfoot>
                   </table>
               </div>
           </div>
       </div>
       <div class="col-md-offset-3 col-md-9">
         {{ $races->links() }}
       </div>
   </div>
</div>


<div class="modal fade" id="formRace" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <form class="modal-content formRace" action="/admin/races" method="POST">
            <input type="hidden" name="_method" id="method" value="PUT"></span>
            {!! csrf_field() !!}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"></h4>

            </div>
            <div class="modal-body col-md-12">
                <div class="form-group col-md-6 col-xs-12">
                    <label for="raceName">Name</label>
                    <input type="text" class="form-control" id="raceName" placeholder="Enter name" name="name" />
                </div>

                <div class="form-group col-md-6 col-xs-12">
                    <label for="raceType">Type</label>
                    <select class="form-control" id="raceType" name="type">
                        <option value="1">Boss</option>
                        <option value="2">Normal</option>
                    </select>
                </div>

                <div class="form-group col-md-6 col-xs-12">
                    <label for="raceHp">HP</label>
                    <input type="text" class="form-control" id="raceHp" placeholder="Enter hp" name="hp" />
                </div>

                <div class="form-group col-md-6 col-xs-12">
                    <label for="raceExp">EXP</label>
                    <input type="text" class="form-control" id="raceExp" placeholder="Enter exp" name="exp" />
                </div>

                <div class="form-group col-md-12 col-xs-12">
                    <label for="raceCoords">Coords</label>
                    <textarea class="form-control coordenadas" id="raceCoords" placeholder="" name="coords" ></textarea>
                </div>

                <div class="form-group col-md-12 col-xs-12 setMap">
                    <iframe src="/map.html" width="540" height="350"></iframe>
                </div>



            </div>
            <div class="modal-footer">
                <input type="hidden" id="raceId" name="id" value="">
                <button type="button" class="btn btn-default cleanForm" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/admin/pages/scripts.blade.php
@extends('admin.layouts.default')

@section('includes')

@stop

@section('content')
<div class="row">
    
    <div class="col-md-12">
       <div class="panel panel-default">
           
           <div class="panel-body">
               @foreach ($result as $r)
               {{ $r }} <br />
               @endforeach
           </div>
 
           
       </div>

   </div>
</div>
@stop